### ISSUE TITLE
[Minor inconvenience] go_router import suggestion triggers warning

### ISSUE THREAD

**Issue by s9th** [csells/go_router#116]
Since 2.2.0 whenever go_router method is used without importing package before, vscode import suggests 
import 'package:go_router/src/go_router.dart';

![image](https://user-images.githubusercontent.com/15362801/139290856-e58f63e3-931e-4b0c-95a9-cf0f0026311a.png)

This in turn produces a warning if corresponding analysis option is enabled, so you need to manually change the import to 'package:go_router/go_router.dart'
![image](https://user-images.githubusercontent.com/15362801/139290943-10893d44-1b10-4645-96ea-70fdac5b1b01.png)

**Comment by csells** [comment]
@s9th that is a bug for sure! @kevmoo what did you do??? : )

**Comment by kevmoo** [comment]
It's a bug – in analyzer! 

https://pub.dev/documentation/go_router/latest/go_router/GoRouterHelper.html

The extension class is exported correctly!

I could imagine this being an edge case w/ extension types – since they are new-ish.

**Comment by csells** [comment]
@s9th this should be fixed in v2.2.4. can you confirm?

**Comment by s9th** [comment]
can confirm, thank you
