### ISSUE TITLE
notifyListeners is not called when using router.go

### ISSUE THREAD

**Issue by esDotDev** [csells/go_router#126]
It seems that `notifyListeners` is only called when using the various imperative .push/.pop, but not when calling `router.go()`.

**Comment by esDotDev** [comment]
The issue was caused by not assigning a `pageKey`, which caused the navigator to be unaware that it's pageStack had changed. Which I suppose is expected :) 

This could be worked around by just adding a manual `notifyListeners` call to `_go` fwiw.

**Comment by csells** [comment]
I'm just using the underlying `Navigator` support for `NavigatorObserver`.

**Comment by esDotDev** [comment]
It looks like you do call `_safeNotifyListeners` from within `goRouterDelegate.go`, this causes the GoRouterDelegate to call `notifyListeners`, but it does not cause `GoRouter` to do the same.

Which creates this edge case: 
* Observers are not notified, when 2 stacks of pages, of the same length, are swapped without keys.

If you wanted to remove this edge case, you could probably do something like:
```
void go(String location, {Object? extra}){
   routerDelegate.go(location, extra: extra);
   notifyListeners(); // just manually let everyone know we changed, since navigator.observers might miss it.
}
```
