### ISSUE TITLE
Does the constructed navigation stack overrides the current stack?

### ISSUE THREAD

**Issue by idkq** [csells/go_router#14]
> "an entire stack of pages can be constructed from the route name alone"

If a user has been navigating on these routes A > B > C (navigation history contains A, B, and C) and types `family/f1` in the browser, does it override the A, B, C history?

How to sync both constructed and real navigation history?

**Comment by csells** [comment]
@idkq yes: when you navigate to `family/f1`, it updates the app's navigate stack based on that URL. There is no way in Flutter to 'sync' the browser and app navigation history. I don't believe there's even a browser API that allows an app to set the browser history which would be required for such a sync.

**Comment by idkq** [comment]
Thanks. My second question relates to the past navigation history in Flutter, not the browser. But if you override, there is no way to sync. Alternatively you could keep A, B, C and append family & f1. So back button would show F1 > Family > C > B > A.

**Comment by csells** [comment]
That's correct -- that's an algorithm I'm considering but haven't yet implemented.

**Comment by csells** [comment]
dup: https://github.com/csells/go_router/issues/9
