### ISSUE TITLE
Add ability to get a stack of GoRoutes that match a given name

### ISSUE THREAD

**Issue by esDotDev** [csells/go_router#152]
There are times when we want to retrieve the .path value for a given route, using the name.

For example, I might have a view that need to check whether it is currently on the search page, but it only has the route name available to use.

So, given this route:
```dart
GoRoute(
  path: '/search/:keywords',
  name: SearchPage.routeName,
)
```
I want to check whether this is my current route somewhere down the tree, using `SearchPage.routeName` to do it:
```dart
string searchPath = router.routesForName(SearchPage.routeName).last.path;
searchPath = searchPath.split['/'].first(); // gets 'search'
if(goRouter.location.contains('/$searchPath/')){
  // we're on the search page
}
```

**Comment by csells** [comment]
I believe this can be built with `GoRouter.of(context).routerDelegate.matches` today.
