### ISSUE TITLE
[Proposal] Change `navigatorBuilder` signature to `(BuildContext, Widget, GoRouterState)`

### ISSUE THREAD

**Issue by esDotDev** [csells/go_router#171]
This would fix a couple of problems with the existing signature:
1) The `Widget?` misleads the reader into thinking child may be null, when it never will, and forces the writer to add a redundant `!` operator.

2) It's awkward to make decisions inside of `navigatorBuilder` without a reference to the router or state, because you can not access the goRouter instance when defining it.
```
class _MyAppState extends State<MyApp> {

  GoRouter goRouter = GoRouter(
    navigatorBuilder: (_, child) {
      if (goRouter.location == '/') return child!; // ERROR: error: The instance member 'goRouter' can't be accessed in an initializer. 
      return MainScaffold(child: child!);
    },
```
I can access the router if I define it as a package level variable, but not when it is inside of a class or method.

[Edit] Actually it will work as a class field, if declared as `late`, which is great. Still no go inside of method though, like `initState`

**Comment by csells** [comment]
fixed in v3.0.0
