### ISSUE TITLE
provide a default `pageBuilder` implementation

### ISSUE THREAD

**Issue by csells** [csells/go_router#173]
`GoRouter` should provide a default implementation of `pageBuilder` that checks for the top-level type of the app, e.g. `MaterialApp`, `CupertinoApp` or `WidgetApp`, and use `MaterialPage`, `CupertinoPage` or `Page` as appropriate based on what it finds. It should also use the `state.pageKey`. This would allow you turn this:

```dart
GoRoute(
  path: '/':
  pageBuilder: (c, s) => MaterialPage<void>(key: s.pageKey, HomePage()),
)
```

into this:

```dart
GoRoute(
  path: '/':
  builder: (c, s) => HomePage(),
)
```

You could still override `pageBuilder` if you want to:
- use a different page type
- pass non-default parameters when creating the page, e.g. a custom key
- create a custom transition

**Comment by csells** [comment]
I'm dropping this part of the proposal as too much magic and easy to do by overriding `pageBuilder` instead:

> In conjunction with this would be the ability to push the `transitionsBuilder` and `transitionsDuration` into the `GoRoute` to simplify how you build a page with custom transition, moving it from this:
> 
> ```dart
> GoRoute(
>     path: '/rotation',
>     pageBuilder: (context, state) => CustomTransitionPage<void>(
>       key: state.pageKey,
>       child: MyTransitionsPage(kind: 'rotation', color: Colors.purple),
>       transitionsBuilder: (context, animation, animation2, child) =>
>           RotationTransition(turns: animation, child: child),
>       transitionDuration: Duration(milliseconds: 500),
>     ),
> ),
> ```
> 
> to this:
> 
> ```dart
> GoRoute(
>     path: '/rotation',
>     builder: (context, state) => MyTransitionsPage(kind: 'rotation', color: Colors.purple),
>     transitionsBuilder: (context, animation, animation2, child) =>
>       RotationTransition(turns: animation, child: child),
>     transitionDuration: Duration(milliseconds: 500),
>   ),
> ),
> ```

**Comment by kevmoo** [comment]
That'll do

**Comment by craiglabenz** [comment]
That'd be a nice bit of boilerplate to abstract

**Comment by csells** [comment]
fixed
