### ISSUE TITLE
URL ending with forward slash `/` should not throw an error 

### ISSUE THREAD

**Issue by osaxma** [csells/go_router#191]
Currently, whenever there's a forward slash at the end of the URL (e.g., ` /books/popular/`), the following error occurs:

```
The following _Exception was thrown Exception during GoRouter navigation:
Exception: no routes for location: /books/popular/
```

I believe it'd be reasonable to treat the following two URLs as the same thing since it's a common behavior among most websites:

```
 /books/popular/
 /books/popular 
```

Simplest use case is when a user modifies the URL manually and leaves the slash up there. It'd be a bad UX if the user receive an error page for such a case.

**Comment by csells** [comment]
You're absolutely right. That should work. I'm take a look.

**Comment by csells** [comment]
v2.3.1 should fix this issue. @osaxma can you please verify?

**Comment by osaxma** [comment]
Thanks Chris -- it's working now 🙏🏽

**Comment by csells** [comment]
Thanks for the bug reports, @osaxma. You're making go_router better.
