### ISSUE TITLE
Future<void> signature for push-like operations

### ISSUE THREAD

**Issue by Lootwig** [csells/go_router#192]
Currently, all operations performing some sort of push don't allow executing an action when that pushed route is removed again, as is possible with the `Future<void> Navigator.pop()` API.

Use case is pushing a route from a modal sheet, but only closing that sheet when the user is done doing some stuff on the pushed route.

**Comment by csells** [comment]
Closed as a duplicate of https://github.com/csells/go_router/issues/138

In the meantime, check this out: https://gorouter.dev/navigator-integration

**Comment by Lootwig** [comment]
Interesting, so just use the plain old Navigator API. Thanks for the quick response.
