### ISSUE TITLE
enable relative routing

### ISSUE THREAD

**Issue by csells** [csells/go_router#20]
e.g. if the current location in `/`, then routing to `foo` will route to `/foo`.

otoh if the current location in `/bar`, then routing to `foo` will route to `/bar/foo`.

otgh routing to `/anything` will disregard the current location.

**Comment by csells** [comment]
e.g.

GoRoute(pattern: '/', ..., routes: [GoRoute(pattern: 'family/:fid', ...)])
would enable the following to work from the FamilyPage or lower:

context.go('family/452')

**Comment by csells** [comment]
won't fix

**Comment by mahmoudatef955** [comment]
I'm having a login screen which can be accessed from both home and settings screen,
 
when I'm at settings screen with path  /home/settings , when routing to login I'm getting  /home/login, but I want /home/settings/login. 

My routes:
 GoRoute(
        path: '/home',
        name: homeScreen,
        builder: (context, state) => const HomeScreen(),
        routes: [
          GoRoute(
            path: 'settings',
            name: settingsScreen,
            builder: (context, state) => const SettingsScreen(),
          ),
          GoRoute(
            path: 'login',
            name: loginWithEmailScreen,
            builder: (context, state) => const EmailLoginScreen(),
          ),

         
        ]),
