### ISSUE TITLE
Back button disappear after push

### ISSUE THREAD

**Issue by jaumard** [csells/go_router#224]
Hello,

On my widget I have a button to open a new page like this:
```
context.push(UserDetailsScreen.route.replaceAll(':id', user.id!));
```

It opens the right page but on that page the back button of the `AppBar` is appearing for 1 second and then disappear. No idea why :( 

I have declared the route like this:
```
GoRoute(
          path: UserDetailsScreen.route,
          pageBuilder: (context, state) => CustomTransitionPage<void>(
            key: state.pageKey,
            transitionsBuilder: (BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
              return FadeTransition(opacity: animation, child: child);
            },
            child: UserDetailsScreen(
              id: state.params['id']!,
            ),
          ),
        ),
```
Route is `static const route = '/admin/healer/:id';`.

Any idea why it may happen? Look like the current route is removed after pushing the new one so no more back button (forcing it to do a pop just make a black screen so history is empty). 

I have another push in my app that is quite similar and it's working well, wondering why this one doesn't work...

**Comment by csells** [comment]
can you post a minimal repro main.dart that I can run on my side and debug?

also, you may this helpful: https://gorouter.dev/debugging

**Comment by jaumard** [comment]
Thanks for the debugging flag! I have enabled it and when I click on the button I see this:
```
flutter: GoRouter: pushing /admin/healer/1ae96979-1b78-4ef8-bb1d-491943fa61b5
flutter: GoRouter: refreshing /admin/healer/1ae96979-1b78-4ef8-bb1d-491943fa61b5
flutter: GoRouter: refreshing /admin/healer/1ae96979-1b78-4ef8-bb1d-491943fa61b5
```

And the full debug from start is:
```
flutter: GoRouter: known full paths for routes:
flutter: GoRouter:   => /404
flutter: GoRouter:   => /500
flutter: GoRouter:   => /
flutter: GoRouter:   => /login
flutter: GoRouter:   => /resetPassword
flutter: GoRouter:   => /admin/healer/:id
flutter: GoRouter:   => /healer/:id
flutter: GoRouter:   => /register
flutter: GoRouter:   => /home
flutter: GoRouter: known full paths for route names:
flutter: GoRouter:   splashscreen => /
flutter: GoRouter:   login => /login
flutter: GoRouter:   resetpassword => /resetPassword
flutter: GoRouter:   register => /register
flutter: GoRouter:   home => /home
flutter: GoRouter: setting initial location /
[sentry] [debug] release: org.ahsi.soinezheureux@1.0.5+0
flutter: GoRouter: refreshing /
flutter: GoRouter: getting location for name: "home"
flutter: GoRouter: redirecting to /home
flutter: GoRouter: refreshing /home
flutter: GoRouter: pushing /admin/healer/1ae96979-1b78-4ef8-bb1d-491943fa61b5
flutter: GoRouter: refreshing /admin/healer/1ae96979-1b78-4ef8-bb1d-491943fa61b5
flutter: GoRouter: refreshing /admin/healer/1ae96979-1b78-4ef8-bb1d-491943fa61b5
```
I'll try to make a minimal repro, but I'm afraid I'll not be able to do it as it appears only on this push, the other one I do is working fine. But I'll try

**Comment by jaumard** [comment]
I've made some tests, looks like the pushing event is good, the back button is here but when the refreshing event is fired the back button is gone. It is not a minimal repo, but my repo where I remove pretty much everything. You can launch it, click on PUSH  ROUTE and it should reproduce the issue. I did my test on iOS simulator only.   

[bug.zip](https://github.com/csells/go_router/files/7675233/bug.zip)

**Comment by jaumard** [comment]
Did you manage to reproduce on your side with that? 

I just notice that on desktop web, doing a pop just doesn't work (as history looks empty for unknown reason), but the back button of chrome works nicely...

**Comment by csells** [comment]
Can you put all of the code needed to reproduce this issue into a single Dart file? The attached zip has a lot of stuff in it.
