### ISSUE TITLE
Deep linking using query params

### ISSUE THREAD

**Issue by adiospace** [csells/go_router#239]
Hi @csells,

ty for the awesome package.

I recently started using `go_router` on a **mobile** app and i have some issues with deep linking to a screen using query parameters.

This works:

`xcrun simctl openurl booted customscheme://example.com/`

Using query parameters doesn't:

```bash
xcrun simctl openurl booted customscheme://example.com/?tab=1

# it returns
no matches found: customscheme://example.com/?tab=1
```

 I image this is a pretty useful case. Is there a way to handle deep linking using query params?

Navigating in the app to `/?tab=1` is working correctly.

**Comment by adiospace** [comment]
Oh man!!!

nevermind, I had to quote the url

```
xcrun simctl openurl booted "customscheme://example.com/?tab=1"
```

**Comment by csells** [comment]
I'm glad you figured it out!
