### ISSUE TITLE
Sometimes showing a black transition screen while pushing to another page

### ISSUE THREAD

**Issue by brain0212** [csells/go_router#242]
I encounter the black transition screen when I have pushed to a different route (e.g. `/clients/detail --> /room/detail`), but then I find that pushing to a sub-route (e.g. `/clients --> /clients/detail`, `/clients --> /clients/detail --> /clients/detail/edit`) will trigger the same issue after 3 or 4 pushing and popping in the app. The black screen exists around 1 second and then the transition animation is triggered and push to the target page.

Flutter: Channel stable, 2.5.3
go_router: 2.5.2

**Comment by lulupointu** [comment]
Could you provide a small example with the steps to follow to trigger the issue?

**Comment by brain0212** [comment]
After checking the code again, I find that the "black transition screen" should be my loading screen, which I forget to wrap it by Scaffold() and thus it is black. I am sorry for any inconvenience that I may have caused by opening this issue. I should have checked my code more comprehensively and carefully.

**Comment by csells** [comment]
No worries, @brain0212 . I'm glad it worked out.
