### ISSUE TITLE
nav_observer example shows go_router diagnostics info in the debug console when it shouldn't

### ISSUE THREAD

**Issue by csells** [csells/go_router#250]
The `debugLogDiagnostics` parameter to the `GoRouter` ctor is false, but the diagnostic logging info is still sent to the debug console.

**Comment by johnpryan** [comment]
My understanding is the the nav observer should print to the console regardless of `debugLogDiagnostics`, since it's just an example of a class that observes route changes and happens to use the Logger API to log them.
