### ISSUE TITLE
need to make the docs switchable by language

### ISSUE THREAD

**Issue by csells** [csells/go_router#266]
https://github.com/csells/go_router/pull/265 added Japanese docs but I don't know of a good way to show them. Ideally there would be a switch that went between EN and JA but I don't know how to do that with docs.pages.

@Salakar thoughts?

cc @toshi-kuji fyi

**Comment by Ehesp** [comment]
It's not currently possible but something we have thought about. We're currently working through a few internal changes so once they're completed we'll have a think about the best api/way to enable locale.

**Comment by toshi-kuji** [comment]
FYI: I've created a temporary [web page](https://zenn.dev/inari_sushio/scraps/01ef7604a4b934) on a tech blog media, which shows the table of contents + link to each section of the doc so that whoever wants to read in Japanese could go through the docs in order.

**Comment by csells** [comment]
Thanks, @toshi-kuji. I've created a temporary link on [the home page of gorouter.dev](https://gorouter.dev) until we have a better solution.
