### ISSUE TITLE
Unable to turn off logging

### ISSUE THREAD

**Issue by pryshrm** [csells/go_router#280]
I am using v 2.5.7 and I see messages like this in the print log of my flutter app:

INFO: GoRouter: getting location for name: "tab", params: {tabid: 1}

I searched in my code and I am sure I am not logging this. I have also set  debugLogDiagnostics:false, while creating GoRouter. 

How can I turn it off?

**Comment by csells** [comment]
This is an issue caused by https://github.com/csells/go_router/pull/225. There's another related bug as well: https://github.com/csells/go_router/issues/250

@johnpryan can you take a look?

**Comment by johnpryan** [comment]
@pryshrm did you do a full restart or just a hot reload? Changes to the `debugLogDiagnostics` parameter don't get applied unless you do a full restart.
