### ISSUE TITLE
Go method does not push to new route

### ISSUE THREAD

**Issue by lucasdidur** [csells/go_router#282]
I have a route something like this

`/prova/:idProva/questao/:ordem`

So when I use `context.go("/prova/123/questao/1")` and then try to go to question 2 `context.go("/prova/123/questao/2")` the page does not update with new data, but shows on the console that is goin to the route "(GoRouter) going to /prova/123/questao/2". 

But when I use `context.push,` works normaly.

**Comment by csells** [comment]
What do your routes look like? What is "normal" behavior to you?

**Comment by lucasdidur** [comment]
I think they should be like `pushReplacement` flutter behavior. Always rebuild the page, if params change.

**Comment by csells** [comment]
Can you post a minimal repro that I can test against?

**Comment by iAmTosuj** [comment]
I have the same problem. The widget's constructor is called, but the build method does not work.

I use a bloc. If I create a bloc instance in the constructor method and pass it to the blocProvider, then after updating the page, a new bloc will be created in the constructor, but the previous blocProvider with the old bloc will remain in the widget tree. I will be able to show an example tomorrow.

**Comment by csells** [comment]
following up here: https://github.com/csells/go_router/discussions/304
