### ISSUE TITLE
[feature request] Future redirect

### ISSUE THREAD

**Issue by ferraridamiano** [csells/go_router#283]
In my app I need to fetch some data from the storage/network and depending on the result of this data I would like to redirect the user to a different page. In the meantime I would like to show a splashscreen.
At the moment I think I cannot do it with this package. A workaround could be to pass the `Future` object to the splash screen and when the result is ready the splashScreen redirect the user to a different page.
A nicer code could be something like this:

```dart
final _router = GoRouter(
    routes: [
        GoRoute(
            path: '/',
            futureRedirect: FutureRedirect(
                future: _myFutureData,
                initialPage: const SplashScreen(),
                redirect: '/page/${_myFutureData}',
            ),
        ),
    ],
);

```

I hope that this feature request makes sense. Anyway thank you for your work!

**Comment by csells** [comment]
Check out these docs: https://gorouter.dev/redirection

And check out this sample: https://github.com/csells/go_router/blob/main/go_router/example/lib/loading_page.dart

**Comment by ferraridamiano** [comment]
Thank you! It is exactly what I need
