### ISSUE TITLE
_AssertionError package:flutter/src/widgets/heroes.dart': Failed assertion: line 639

### ISSUE THREAD

**Issue by berbsd** [csells/go_router#309]
I am running this issue (similar to #169) and it's been puzzling me for a couple of days.  The stack is copied below. I did create a [sample project](https://github.com/berbsd/crash_sample_app.git) to show the issue. I would appreciate if someone could take a look and point me to a solution or a better approach. 

════════ Exception caught by scheduler library ══════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/heroes.dart': Failed assertion: line 639 pos 12: '() {
package:flutter/…/widgets/heroes.dart:1
      final Animation<double> initial = initialManifest.animation;
      assert(initial != null);
      final HeroFlightDirection type = initialManifest.type;
      assert(type != null);
      switch (type) {
        case HeroFlightDirection.pop:
          return initial.value == 1.0 && initialManifest.isUserGestureTransition
              // During user gesture transitions, the animation controller isn't
              // driving the reverse transition, but should still be in a previously
              // completed stage with the initial value at 1.0.
              ? initial.status == AnimationStatus.completed
              : initial.status == AnimationStatus.reverse;
        case HeroFlightDirection.push:
          return initial.value == 0.0 && initial.status == AnimationStatus.forward;
      }
    }()': is not true.

**Comment by berbsd** [comment]
found workaround for now

**Comment by csells** [comment]
Good news!

**Comment by chungonion** [comment]
> found workaround for now

Hi there, I am facing a similar issue (although the app does not crash), just wonder what is the workaround for that? Thank you!
