### ISSUE TITLE
Missing `HeroController` inheritance

### ISSUE THREAD

**Issue by benPesso** [csells/go_router#314]
According to [this article](https://docs.flutter.dev/release/breaking-changes/hero-controller-scope), if you're not using Navigator 1.0, `Hero`s will essentially not work, as they rely on a `HeroController` provided by `Navigator` to conduct their transitions.

Took me a good while to figure out why Hero animations were not working with `GoRouter`, until I accidently stumbled on this little gem of an article - which I doubt many others are familiar with - and managed to get it working.

<details>
<summary>By wrapping with a <code>HeroControllerScope</code> widget:</summary>

```dart
MaterialApp(
  home: HeroControllerScope(
    controller: HeroController(),
    child: Router(
      routerDelegate: _router.routerDelegate,
      routeInformationParser: _router.routeInformationParser,
    ),
  ),
  ...
);
```
</details>

Or...
<details>
<summary>by adding a <code>HeroController</code> observer:</summary>

```dart
_router = GoRouter(
  observers: [HeroController()],
  ...
);
```
</details>

Ideally, GoRouter should include a `HeroController` observer by default (with option to override, for tween behavior modification). At the very least, the [GoRouter > Transitions](https://gorouter.dev/transitions) section should probably mention something about Hero animations and how to get them working with GoRouter.

**Comment by csells** [comment]
Cool! Would you like to propose a new sample that supports Hero graphics in a PR along with some updates to the docs?

**Comment by benPesso** [comment]
Yeah sure. Just need to iron out some kinks with Hero animation jitter first. 😶

**Comment by csells** [comment]
closing this due to lack of customer input. feel free to reopen it if you have a minimal repro.
