### ISSUE TITLE
Missing `state.extra` in GoRouterState from NavigatorBuilder

### ISSUE THREAD

**Issue by bkoznov** [csells/go_router#318]
It seems like the state that navigatorBuilder has access has `state.extra` always being `null`. I poked around in the docs and the code & couldn't suss out a reason for this. Made a quick and dirty change to the code and it seems to to work?

Ideal behavior would be that extra is available to navigatorBuilder or documentation clearly explains what the state in navigatorBuilder is missing and why.

This package has been a joy to use, appreciate all the work done on it!

**Comment by csells** [comment]
Discussed here: https://github.com/csells/go_router/pull/319#issuecomment-1016853775
