### ISSUE TITLE
Add complete basic routes handling as Flutter Navigator

### ISSUE THREAD

**Issue by nicolasvac** [csells/go_router#330]
GoRouter as of now is lacking behind the current methods available by the flutter navigator.

Currently missing to get at least the basics completely working:

- [ ] Navigator.removeRoute https://api.flutter.dev/flutter/widgets/Navigator/removeRoute.html
- [ ] Navigator.popUntil https://api.flutter.dev/flutter/widgets/Navigator/popUntil.html
- [ ] Navigator.pushAndRemoveUntil https://api.flutter.dev/flutter/widgets/Navigator/pushAndRemoveUntil.html
- [ ] Navigator.replace https://api.flutter.dev/flutter/widgets/Navigator/replace.html

**Comment by csells** [comment]
That's a good feature request

**Comment by jamolina2021** [comment]
These features are essential. :)

**Comment by csells** [comment]
PRs graciously accepted. : )
