### ISSUE TITLE
possibility to have several subroutes under the same specific route.

### ISSUE THREAD

**Issue by OppositeDragon** [csells/go_router#354]
Is it possible to have several subroutes for a specific route?

I have been getting an error, I tried more than one subroute, but the framework complained saying too many routes. 

If it is possible, how would one achieve it? if not, can it be explained why?

**Comment by II11II** [comment]
> Is it possible to have several subroutes for a specific route?
> 
> I have been getting an error, I tried more than one subroute, but the framework complained saying too many routes.
> 
> If it is possible, how would one achieve it? if not, can it be explained why?

Please, share the minimum  code repo to get this error

**Comment by OppositeDragon** [comment]
I figured out what is it that I was doing wrong. I guess it should be stated on the docs that subroutes need a part of the path to be different, not only from the parameters they take.
