### ISSUE TITLE
Support for flutter_riverpod

### ISSUE THREAD

**Issue by rddewan** [csells/go_router#373]
Is there any support to use it with flutter_riverpod.

**Comment by RandalSchwartz** [comment]
What doesn't work with riverpod?

**Comment by rddewan** [comment]
refresh listener and redirect does not work it keeps on looping

**Comment by csells** [comment]
Can you provide a minimal repro project?

**Comment by rddewan** [comment]
Here is the sample project i am working with on Flutter Riverpod and go_router. Every thing works good except just want to listen to logout state notifier
https://github.com/rddewan/flutter-note
