### ISSUE TITLE
Any thoughts on implementing "MiddleWare" to support deferred libraries?

### ISSUE THREAD

**Issue by PcolBP** [csells/go_router#374]
Hi, I'm in middle of developing Web page in Flutter. The deeper I go the main file called main.dart.js is getting bigger. So then I've started searching how to reduce the file size.  

I came across to that [article](https://medium.com/@SchabanBo/reduce-your-flutter-web-app-loading-time-8018d8f442) and found out about deferred libraries. That sample project from article is based on [qlevar_router](https://pub.dev/packages/qlevar_router) which has such handy method as Middleware which helps in implementing separate file for each page.

Since my project is based on your awesome package GoRouter, I was thinking about if are you planning to implement this or haven't thought about it yet? 
Please let me know if its interesting enhancement for your package.

**Comment by csells** [comment]
that's an interesting idea!
