### ISSUE TITLE
pressing AppBar Back button after a push() doesn't refresh the brower's address bar

### ISSUE THREAD

**Issue by csells** [csells/go_router#40]
until a `go` or another `push`

can repro by running [the push sample](https://github.com/csells/go_router/blob/master/example/lib/push.dart), pressing the button to push a route and then pressing the Back button the AppBar.

**Comment by doughywilson** [comment]
I can confirm that the URL is updated correctly on the next call to push() or pushNamed().

**Comment by csells** [comment]
@doughywilson I think this is fixed in v1.0.1. Please give it a try.

**Comment by doughywilson** [comment]
> @doughywilson I think this is fixed in v1.0.1. Please give it a try.

Boom! Works great! Thanks for the fast fix!!

**Comment by csells** [comment]
great! thanks for the help, @slightfoot!

**Comment by slightfoot** [comment]
Your welcome @csells
