### ISSUE TITLE
Navigational Observers

### ISSUE THREAD

**Issue by shriharip** [csells/go_router#46]
Hello,

Thanks for all the effort here. I have a question related to using of navigational observers. How can we use them with go_router?
For example third party apps like FirebaseAnalyticsObserver that need to be passed to this router. 

Best,
Hari

**Comment by csells** [comment]
I added support in v1.1.0. Give it a try and let me know if it's working.

**Comment by shriharip** [comment]
Thanks Chris, that was super quick. I have added it. Somehow the Firebase tracking is not happening. But I think it is a different issue. I will keep you posted on this. Regards Hari

**Comment by csells** [comment]
Hey, @rkunboxed. v2.5.2 adds some add'l data to the `NavigatorObserver` by default if you're using the new `builder` methods in your routes as described here: https://gorouter.dev/migrating-to-25
