### ISSUE TITLE
Is there any way to do something similar to pushReplacement? 

### ISSUE THREAD

**Issue by Ch4v3-98** [csells/go_router#53]
In my App I need to a do a Push within the same Path multiple times, so can't use "context.go" because it doesn't go through the initState. And doing a "context.push) to the same Route it's bad for performance and for example, when there are Controllers for ListViews, it starts showing errors because the same Controller is attached to multiple views in the Stack. Couldn't find anything in the documentation about this. Thanks!

**Comment by csells** [comment]
Can you describe what problem you're trying to solve?

There's no routing perf problem with pushing the same route onto the navigation stack multiple times. You can see a sample of doing just that in the [push example](https://github.com/csells/go_router/blob/master/example/lib/push.dart).

**Comment by Ch4v3-98** [comment]
> Can you describe what problem you're trying to solve?
> 
> There's no routing perf problem with pushing the same route onto the navigation stack multiple times. You can see a sample of doing just that in the [push example](https://github.com/csells/go_router/blob/master/example/lib/push.dart).

Then I'm pretty sure it's because the way I handle states (and probably performance in general). I thougt it was pushing a new route on top of the other without completly disposing the previous one. As for the ScrollControllers problem, already fixed it by initializing it every time in the initState() rather than it being final. Thanks, amazing package by the way, really easy to use!

**Comment by csells** [comment]
@Ch4v3-98 I'm glad you're enjoying it! Keep those cards and letters coming!
